export const houses = [
  {
    user_id: 1,
    title: 'Casa de Campo con Piscina',
    description: 'Casa de campo con 3 habitaciones, 2 baños, piscina y amplios jardines. Perfecta para escapadas de fin de semana.',
    imageSrc: ['../src/assets/1.jpg','../src/assets/2.jpg', '../src/assets/3.jpg'],
    createdAt: '2022-01-10',
    category: 'chalet',
    roomCount: 3,
    bathroomCount: 2,
    guestCount: 6,
    locationValue: '40.7128, -74.0060', 
    amenities: ['wifi', 'parking', 'air conditioned'],
    price: 200,

  }, 
  {
    user_id: 2,
    title: 'Casa Rústica en las Montañas',
    description: 'Acogedora casa de campo con 3 habitaciones, 2 baños y hermosas vistas a las montañas. Perfecta para escapadas de fin de semana.',
    imageSrc: [],
    createdAt: '2022-04-01',
    category: 'chalet',
    roomCount: 3,
    bathroomCount: 2,
    guestCount: 6,
    locationValue: '34.0522, -118.2437', // Coordenadas de Los Ángeles
    price: 150,
    amenities: ['wifi', 'parking', 'air conditioned'],
  },
  {
    user_id: 3,
    title: 'Apartamento Moderno en el Centro de la Ciudad',
    description: 'Elegante apartamento con 1 habitación y todas las comodidades modernas. Ubicación conveniente en el corazón de la ciudad.',
    imageSrc: ['../src/assets/3.jpg'],
    createdAt: '2022-05-10',
    category: 'apartament',
    roomCount: 1,
    bathroomCount: 1,
    guestCount: 2,
    locationValue: '51.5074, -0.1278', // Coordenadas de Londres
    price: 90,
    amenities: ['wifi', 'parking', 'air conditioned'],
  },
  {
    user_id: 4,
    title: 'Loft Moderno en el Centro Histórico',
    description: 'Espacioso loft con diseño contemporáneo. 2 habitaciones, 2 baños y vistas impresionantes al centro histórico.',
    imageSrc: ['../src/assets/4.jpg'],
    createdAt: '2022-06-20',
    category: 'apartament',
    roomCount: 2,
    bathroomCount: 2,
    guestCount: 4,
    locationValue: '40.4168, -3.7038', // Coordenadas de Madrid
    price: 180,
    amenities: ['wifi', 'parking', 'air conditioned'],
  },
  {
    user_id: 5,
    title: 'Villa con Piscina en la Costa Mediterránea',
    description: 'Villa de lujo con 5 habitaciones, 4 baños, amplios jardines y piscina privada. Acceso directo a la playa.',
    imageSrc: ['../src/assets/5.jpg'],
    createdAt: '2022-07-12',
    category: 'flat',
    roomCount: 5,
    bathroomCount: 4,
    guestCount: 10,
    locationValue: '41.9028, 12.4964', // Coordenadas de Roma
    price: 350,
    amenities: ['wifi', 'parking', 'air conditioned'],
  },
  {
    user_id: 6,
    title: 'Cabaña Acogedora en el Bosque',
    description: 'Cabaña rodeada de naturaleza con 1 habitación, chimenea y todas las comodidades para una escapada tranquila.',
    imageSrc: ['../src/assets/6.jpg'],
    createdAt: '2022-08-05',
    category: 'chalet',
    roomCount: 1,
    bathroomCount: 1,
    guestCount: 2,
    locationValue: '45.4215, -75.6993', // Coordenadas de Ottawa
    price: 80,
    amenities: ['wifi', 'parking', 'air conditioned'],
  },
  {
    user_id: 7,
    title: 'Apartamento con Vista al Parque',
    description: 'Moderno apartamento con 2 habitaciones, balcón y vistas panorámicas al parque cercano.',
    imageSrc: ['../src/assets/7.jpg'],
    createdAt: '2022-09-18',
    category: 'apartament',
    roomCount: 2,
    bathroomCount: 1,
    guestCount: 4,
    locationValue: '48.8566, 2.3522', // Coordenadas de París
    price: 130,
    amenities: ['wifi', 'parking', 'air conditioned'],
  },
  {
    user_id: 8,
    title: 'Casa de Playa con Acceso Privado',
    description: 'Encantadora casa de playa con 3 habitaciones, terraza y acceso directo a la playa privada.',
    imageSrc: ['../src/assets/8.jpg'],
    createdAt: '2022-10-02',
    category: 'chalet',
    roomCount: 3,
    bathroomCount: 2,
    guestCount: 6,
    locationValue: '25.7617, -80.1918', // Coordenadas de Miami
    price: 220,
    amenities: ['Wifi', 'Parking', 'Air Conditioned'],
  },
  {
    user_id: 9,
    title: 'Chalet en las Montañas',
    description: 'Chalet acogedor con 4 habitaciones, chimenea y espectaculares vistas a las montañas circundantes.',
    imageSrc: ['../src/assets/9.jpg'],
    createdAt: '2022-11-15',
    category: 'chalet',
    roomCount: 4,
    bathroomCount: 3,
    guestCount: 8,
    locationValue: '47.6062, -122.3321', // Coordenadas de Seattle
    price: 180,
    amenities: ['wifi', 'parking', 'air conditioned'],
  },
  {
    user_id: 10,
    title: 'Apartamento Elegante en el Centro',
    description: 'Apartamento con diseño elegante, 1 habitación y comodidades modernas. Ubicación céntrica y accesible.',
    imageSrc: ['../src/assets/10.jpg'],
    createdAt: '2022-12-05',
    category: 'apartament',
    roomCount: 1,
    bathroomCount: 1,
    guestCount: 2,
    locationValue: '52.5200, 13.4050', // Coordenadas de Berlín
    price: 100,
    amenities: ['wifi', 'parking', 'air conditioned'],
  },
  {
    user_id: 11,
    title: 'Casa Colonial en el Casco Antiguo',
    description: 'Casa histórica con encanto colonial, 3 habitaciones y patio interior. Ubicada en el casco antiguo de la ciudad.',
    imageSrc: ['../src/assets/11.jpg'],
    createdAt: '2023-01-10',
    category: 'chalet',
    roomCount: 3,
    bathroomCount: 2,
    guestCount: 6,
    locationValue: '-34.6037, -58.3816', // Coordenadas de Buenos Aires
    price: 190,
    amenities: ['wifi', 'parking', 'air conditioned'],
  },
  {
    user_id: 12,
    title: 'Villa de Lujo con Piscina Infinita',
    description: 'Impresionante villa con 5 habitaciones, piscina infinita y vistas panorámicas al mar. Experiencia de lujo.',
    imageSrc: ['../src/assets/12.jpg', '../src/assets/3.jpg', '../src/assets/4.jpg'],
    createdAt: '2023-02-20',
    category: 'chalet',
    roomCount: 5,
    bathroomCount: 4,
    guestCount: 10,
    locationValue: '33.6844, -117.8265', // Coordenadas de Newport Beach
    price: 400,
  },
  {
    user_id: 13,
    title: 'Casa Moderna con Jardín Exuberante',
    description: 'Elegante casa moderna con un hermoso jardín, perfecta para relajarse y disfrutar de la naturaleza.',
    imageSrc: [],
    createdAt: '2023-03-15',
    category: 'chalet',
    roomCount: 4,
    bathroomCount: 3,
    guestCount: 8,
    locationValue: '34.0522, -118.2437', // Coordenadas de Los Ángeles
    price: 300,
  },
  {
    user_id: 13,
    title: 'Casa Moderna con Jardín Exuberante',
    description: 'Elegante casa moderna con un hermoso jardín, perfecta para relajarse y disfrutar de la naturaleza.',
    imageSrc: [],
    createdAt: '2023-03-15',
    category: 'chalet',
    roomCount: 4,
    bathroomCount: 3,
    guestCount: 8,
    locationValue: '34.0522, -118.2437', // Coordenadas de Los Ángeles
    price: 300,
  },
  {
    user_id: 14,
    title: 'Mountain house ski resort',
    description: 'In front of the ski resort of Pas de la Casa.',
    imageSrc: ['../src/assets/12.jpg', '../src/assets/3.jpg', '../src/assets/4.jpg'],
    createdAt: '2023-03-15',
    category: 'chalet',
    roomCount: 4,
    bathroomCount: 3,
    guestCount: 8,
    locationValue: '42.5427700, 1.7336100', 
    price: 350,
    amenities: ['Wifi', 'Parking', 'Air Conditioned'],
  },
  {
    user_id: 15,
    title: 'Mountain house Andorra',
    description: 'Close to the shops and restaurants of the village of Arinsal, this chalet is a great option for a family or group of friends looking for a comfortable stay in the mountains.',
    imageSrc: ['../src/assets/1.jpg', '../src/assets/2.jpg', '../src/assets/4.jpg'],
    createdAt: '2023-03-15',
    category: 'chalet',
    roomCount: 4,
    bathroomCount: 3,
    guestCount: 8,
    locationValue: '42.5077900, 1.5210900', 
    price: 350,
    amenities: ['Wifi', 'Parking', 'Air Conditioned', 'Elevator'],
  },
  {
    user_id: 16,
    title: 'Downtown apartment Andorra',
    description: 'Close to the shops and restaurants of the village of Arinsal, this chalet is a great option for a family or group of friends looking for a comfortable stay in the mountains.',
    imageSrc: ['../src/assets/10.jpg', '../src/assets/3.jpg', '../src/assets/4.jpg'],
    createdAt: '2023-03-15',
    category: 'apartment',
    roomCount: 2,
    bathroomCount: 2,
    guestCount: 4,
    locationValue: '42.50317, 1.51313', 
    price: 350,
    amenities: ['Wifi', 'Parking', 'Air Conditioned', 'Elevator'],
  },



]

export default houses; 